name: Update GitHub Stats

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with current date
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d")
          echo "🔄 Last updated: $CURRENT_DATE"
          
          # Add or update last updated timestamp
          if grep -q "Last updated:" README.md; then
            sed -i "s/Last updated: .*/Last updated: $CURRENT_DATE/" README.md
          else
            echo "" >> README.md
            echo "---" >> README.md
            echo "Last updated: $CURRENT_DATE" >> README.md
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "📅 Update timestamp: $CURRENT_DATE"
          git push